name: Build
on: 
  push:
    branches:
      - master
jobs:
    build:
        name: Build
        runs-on: windows-latest
        steps:
          - name: Git Checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 1
          - name: Set up MSVC environment
            uses: ilammy/msvc-dev-cmd@v1.9.0
          - name: Build Release
            shell: pwsh
            run: |
              Install-Package Microsoft.Exchange.WebServices -Version 2.2.0
              mkdir build
              cd build
              cmake -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX="../installed" ../
              cmake --build .
          - name: Create Package
            run: |
              cd build
              cpack -G ZIP
          - name: Publish Artifact
            uses: actions/upload-artifact@v2
            with:
                name: ExchangeWorker
                path: |
                  build/ExchangeWorker.zip
